### ISSUE TITLE
Compiling current FR code with MSVC 2019 fails 

### ISSUE THREAD

**Issue by tester0077** [mariuz/flamerobin#172]
When I try to build FR with wxWidgets 3.1.4 under MSVC 2019 for 32-bits static debug, I get a number of warnings, but also one error 

_1>DataGridRows.cpp
1>D:\pkg\wx\MSVC2019\_3.1.4_2019\flamerobin-git\src\gui\controls\DataGridRows.cpp(1269,53): error C2440: 'type cast': cannot convert from 'DataGridRowBuffer' to 'unsigned char'
1>D:\pkg\wx\MSVC2019\_3.1.4_2019\flamerobin-git\src\gui\controls\DataGridRows.cpp(1269,25): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>Done building project "flamerobin_flamerobin.vcxproj" -- FAILED._

The warnings I can either live with or fix, but this error, is a show stopper for me.

**Comment by arvanus** [comment]
Hi, could please test under VS2015?
Thanks

**Comment by tester0077** [comment]
No, in the latest code from your Github,  is is in the block 1221 - 1237
_else    // binary (show as hexadecimal)
        {
            for (int i=0; i<size; i+=8)
            {
                int last = 8;
                if (i+last >= size)
                    last = size - i;
                for (int j=0; j<last; j++)
                {
                    result += wx2std(wxString::Format("%02X",
                        (unsigned char)(buffer[i+j])));   <<<<<<<<<<<<<<<<<<<<<
                }
                result += " ";
                if (((i + 8) % 32) == 0)
                    result += "\n";
            }
        }_
I have compiled the latest code from this site using SVC 2015 and wxWidgets 3.1.1 and many of the warnings in the code I have are fixed, though some are still there and others are new.
Still it all compiles with MSVC 2015.
Will give 2019 a try; the MSVC's compilers get fussier with every release ;-)

**Comment by tester0077** [comment]
Some of the warnings for MMSVC 2019 & wxWidgets 3.1.4 can be avoided 
StartStyling(0, 0);  ==>         StartStyling(0);
font.SetWeight(wxBOLD);    ==>     font.SetWeight(wxFONTWEIGHT_BOLD );

wxFont font(frlayoutconfig().getEditorFontSize(), wxMODERN, wxNORMAL, wxNORMAL);     ==>

wxFont font(frlayoutconfig().getEditorFontSize(),wxFONTFAMILY_MODERN,  wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, wxFONTFLAG_DEFAULT );

along with some unused args, such as wxString Package::getAlterSql(bool WXUNUSED(full))

**Comment by arvanus** [comment]
The question about wxWidgets 3.1.4 warnings... it's not fixed yet to keep compatibility with 3.0, and to migrate directly to 3.2 (or something like that)

**Comment by arvanus** [comment]
About VS2019, I just downloaded and prepared with CMake and was able to build normally without errors
Did you used CMake too?
Thanks

**Comment by tester0077** [comment]
No, I converted the older MSVC .sln file
I only use CMake if I have to :-)
Yes.  upgrading even in wxWidgets does cause some issues. 
Getting rid of warnings just makes it easier to spot 'real' problems, though most warnings can be suppressed with compiler /wdxxxx options
Still, I am very happy to see FR is not dead :-)

**Comment by arvanus** [comment]
Hi. I'm closing this issue as I can compile Flamerobin with VS2022. Also now you need to use CMake to create the project now
