### ISSUE TITLE
Looks like Flamerobin is subtracting the timezone again or something like that.

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#338]
![image](https://github.com/mariuz/flamerobin/assets/8182958/61b71823-6f2c-476d-b09c-918198a93454)
--set time zone 'America/Sao_paulo';
--set bind of time with time zone to legacy;
--set bind of timestamp with time zone to legacy;
select localtime, current_time, CURRENT_TIMESTAMP from rdb$database

Both columns should have the same timestamp value for Fb4+

**Comment by arvanus** [comment]
See more here:
https://github.com/FirebirdSQL/firebird/issues/7806#issuecomment-1766296875

**Comment by arvanus** [comment]
@andy-123 can you take a look?
Looks like we need to load ICU someway, and convert every single field to the specific offset taking account the timezone and time itself 
I don't know if we can do it using directly fbclient.dll or just by using ICU dll 
For now I'm thinking to change Flamerobin behavior to always show time as GMT+0:00 to avoid misinterpretation of the value

**Comment by andy-123** [comment]
I'm sorry for being late. I hope to find time for this in the next few weeks.

**Comment by arvanus** [comment]
Note: probably the correct place to change it could be at IBPP source, not sure

**Comment by andy-123** [comment]
See PR (Draft) #362 for current state.

**Comment by andy-123** [comment]
@arvanus 
The PR is almost finished. Unfortunately, the time displayed (localtime/current_time) in the time zone "America/Sao_Paulo" does not match what isql shows. (See also the description in the PR).

It's unclear to me where the BUG comes from.
When debugging isql, I noticed that the DST (Daylight save time) for America/Sao_Paulo is added here. This is responsible for the one hour difference. Sao_Paulo abolished the DST in 2019. This indicates an outdated ICU version. However, my linux and also fbclient/isql seem to have a current version of ICU.
And why is isql correct?
I currently have no idea how to solve this problem. Maybe someone here can help and give a good hint or something.

**Comment by arvanus** [comment]
Hi, I'll take a look what it could be ASAP
Thanks

**Comment by andy-123** [comment]
Thank you.
Maybe this is still helpful:
It depends on the DST (Daylight saving time). With PR #362 applied, the time is displayed correctly if you subtract or add 1/2 year.
![grafik](https://github.com/mariuz/flamerobin/assets/35083838/3915df87-9dab-4a77-ac7a-513ea75a15ce)

**Comment by arvanus** [comment]
SO, I tried this SQL in a "legacy" Firebird 4.0
```

select  localtime, localtimestamp, current_time, CURRENT_TIMESTAMP, 
        cast(localtime as varchar(42)) as cast_localtime, 
        cast(localtimestamp as varchar(42)) as cast_localtimestamp, 
        cast(current_time as varchar(42)) as cast_current_time, 
        cast(CURRENT_TIMESTAMP as varchar(42)) as cast_CURRENT_TIMESTAMP
      from rdb$database

```
And is showing the same time correctly 
![image](https://github.com/mariuz/flamerobin/assets/8182958/08254f7b-c751-4e54-a9f1-893e47a440de)


BUT in another server I get the time with +1Hour, very strange :

![image](https://github.com/mariuz/flamerobin/assets/8182958/e2a7c04d-1cd5-4fb7-94ce-f092333ffdc1)

(also in isql)
![image](https://github.com/mariuz/flamerobin/assets/8182958/b795de85-b063-44f7-9d77-59151ba2ad0d)

When I try in another server with timezone (America/Sao_paulo) manually defined in the conf , I get another behaviour

![image](https://github.com/mariuz/flamerobin/assets/8182958/d8a6391b-7789-448d-91e9-463ea882388d)
![image](https://github.com/mariuz/flamerobin/assets/8182958/3061581e-ef9a-48b4-a9f3-cdda85506e94)

Note: I'm in a hurry now, so maybe I missed something

**Comment by andy-123** [comment]
Thanks for testing. Very strange, ...
Is isql embedded or connected via network? I suspect that this makes a difference.
In the first isql query, the time zone is displayed as "-3:00". This could be a problem loading the ICU library.

**Comment by arvanus** [comment]
Via network, remote servers.
Also noted that if the server is using the default OS timezone, or is using a fixed in firebird.conf equal to the OS timezone I get different results somehow

**Comment by arvanus** [comment]
@andy-123 I found some strange behavior related with manually setting DefaultTimeZone = America/Sao_paulo
When not defined the output is correct, but the TZ is odd

I submitted a post at firebird-support 
https://groups.google.com/g/firebird-support/c/5FA5R8Pjvog/m/EBqlQ-AwAwAJ

SQL:
```
select  localtime, current_time, 
        cast(localtime as varchar(42)) as cast_localtime, 
        cast(current_time as varchar(42)) as cast_current_time
    from rdb$database
```
with `DefaultTimeZone = `
![image](https://github.com/mariuz/flamerobin/assets/8182958/1ea4acd1-f9d4-46ee-b264-46c180d7034c)


with `DefaultTimeZone =  America/Sao_paulo`
![image](https://github.com/mariuz/flamerobin/assets/8182958/e9c896d1-09e7-422a-9db8-16e1ced1e1b3)

**Comment by andy-123** [comment]
I created a small Lazarus project that has the same time problem as flamerobin. I have created a support request for this.
https://groups.google.com/g/firebird-support/c/vic0_wwpOVw

**Comment by andy-123** [comment]
No, unfortunately there was no helpful answer to either your or my support request.
My two options that I still see are:
Either to find a tool that uses the Firebird API “correctly” and then to be able to apply this knowledge to Flamerobin. 
The other option would be to use icu directly. 
I still have a little time this week, but I'll start pursuing these two options.
